name: Main CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project (if script exists)
        run: npm run build --if-present

      - name: Run tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project (if script exists)
        run: npm run build --if-present

      - name: Deploy to Netlify
        run: |
          npx netlify deploy --dir=build \
            --prod \
            --auth="${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            --site="${{ secrets.NETLIFY_SITE_ID }}"
